### ISSUE TITLE
Shell has to be set so a user is exported to phone list

### ISSUE THREAD

**Issue by miterion** [d120/ldap-web#2]
Is it really necessary to have a shell set so a user appears in the phone list?

https://github.com/d120/ldap-web/blob/d4839e7cd4d3f0fcdaaeaf08d0c52867aa9ab9ec/listusers.php#L43

**Comment by max-weller** [comment]
I guess I wouldn't have implemented this filter if it wasn't necessary ^^

Ich vermute mal, dass der Filter dazu gedacht ist, alte gesperrte Accounts aus der Liste rauszufiltern.

**Comment by Miterion** [comment]
Ich finde die letzteren beiden auch sinnvoll, nur die Erste Option macht wenig Sinn, wenn neue User keine Shell gesetzt bekommen.
